--------------------------------------------------------
-- Archivo creado  - martes-julio-23-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROYECTOS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PROYECTOS" 
   (	"ID_PROYECTO" NUMBER(*,0), 
	"NOMBRE_PROYECTO" VARCHAR2(75 BYTE), 
	"DESCRIPCION_PROYECTO" VARCHAR2(200 BYTE), 
	"FECHA_INICIO" DATE, 
	"FECHA_FIN" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECURSOS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RECURSOS" 
   (	"ID_RECURSO" NUMBER, 
	"NOMBRE_RECURSO" VARCHAR2(50 BYTE), 
	"HABILIDADES" VARCHAR2(200 BYTE), 
	"DISPONIBILIDAD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TAREAS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TAREAS" 
   (	"ID_TAREA" NUMBER(*,0), 
	"ID_PROYECTO" NUMBER(*,0), 
	"NOMBRE_TAREA" VARCHAR2(40 BYTE), 
	"DESCRIPCION_TAREA" VARCHAR2(200 BYTE), 
	"FECHA_VENCIMIENTO" DATE, 
	"ESTADO" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TAREAS
SET DEFINE OFF;
Insert into SYSTEM.TAREAS (ID_TAREA,ID_PROYECTO,NOMBRE_TAREA,DESCRIPCION_TAREA,FECHA_VENCIMIENTO,ESTADO) values (1,1,'Backlog
','Inicio',to_date('21/07/24','DD/MM/RR'),'31/07/2024');
Insert into SYSTEM.TAREAS (ID_TAREA,ID_PROYECTO,NOMBRE_TAREA,DESCRIPCION_TAREA,FECHA_VENCIMIENTO,ESTADO) values (2,1,'Desarrollo','Desarrollo',to_date('01/08/24','DD/MM/RR'),'30/08/24');
Insert into SYSTEM.TAREAS (ID_TAREA,ID_PROYECTO,NOMBRE_TAREA,DESCRIPCION_TAREA,FECHA_VENCIMIENTO,ESTADO) values (3,2,'Backlog','Inicio',to_date('21/07/24','DD/MM/RR'),'31/07/24');

--------------------------------------------------------
--  DDL for Table ASIGNACION_RECURSOS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ASIGNACION_RECURSOS" 
   (	"ID_ASIGNACION" NUMBER, 
	"ID_PROYECTO" NUMBER, 
	"ID_RECURSO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ASIGNACION_RECURSOS
SET DEFINE OFF;
Insert into SYSTEM.ASIGNACION_RECURSOS (ID_ASIGNACION,ID_PROYECTO,ID_RECURSO) values (1,1,2);
Insert into SYSTEM.ASIGNACION_RECURSOS (ID_ASIGNACION,ID_PROYECTO,ID_RECURSO) values (2,2,1);

--------------------------------------------------------
--  DDL for Table REGISTRO_TIEMPO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."REGISTRO_TIEMPO" 
   (	"ID_REGISTRO" NUMBER(*,0), 
	"ID_TAREA" NUMBER(*,0), 
	"ID_RECURSO" NUMBER(*,0), 
	"TIEMPO_INVERTIDO" NUMBER(5,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PROYECTOS
SET DEFINE OFF;
Insert into SYSTEM.PROYECTOS (ID_PROYECTO,NOMBRE_PROYECTO,DESCRIPCION_PROYECTO,FECHA_INICIO,FECHA_FIN) values (1,'Prueba','Nuevo proyecto',to_date('21/06/24','DD/MM/RR'),to_date('31/07/24','DD/MM/RR'));
Insert into SYSTEM.PROYECTOS (ID_PROYECTO,NOMBRE_PROYECTO,DESCRIPCION_PROYECTO,FECHA_INICIO,FECHA_FIN) values (2,'Prueba 2','Esto es una prueba',to_date('25/06/24','DD/MM/RR'),to_date('05/08/24','DD/MM/RR'));
REM INSERTING into SYSTEM.RECURSOS
SET DEFINE OFF;
Insert into SYSTEM.RECURSOS (ID_RECURSO,NOMBRE_RECURSO,HABILIDADES,DISPONIBILIDAD) values (1,'Carlos ','Java, Python','50%');
Insert into SYSTEM.RECURSOS (ID_RECURSO,NOMBRE_RECURSO,HABILIDADES,DISPONIBILIDAD) values (2,'Anres','Java','60%');
REM INSERTING into SYSTEM.REGISTRO_TIEMPO
SET DEFINE OFF;
Insert into SYSTEM.REGISTRO_TIEMPO (ID_REGISTRO,ID_TAREA,ID_RECURSO,TIEMPO_INVERTIDO) values (1,1,1,10);
--------------------------------------------------------
--  DDL for Index PROYECTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PROYECTOS_PK" ON "SYSTEM"."PROYECTOS" ("ID_PROYECTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECURSOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."RECURSOS_PK" ON "SYSTEM"."RECURSOS" ("ID_RECURSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TAREAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TAREAS_PK" ON "SYSTEM"."TAREAS" ("ID_TAREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  DDL for Index ASIGNACION_RECURSOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ASIGNACION_RECURSOS_PK" ON "SYSTEM"."ASIGNACION_RECURSOS" ("ID_ASIGNACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  DDL for Index REGISTRO_TIEMPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."REGISTRO_TIEMPO_PK" ON "SYSTEM"."REGISTRO_TIEMPO" ("ID_REGISTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PROYECTOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PROYECTOS" MODIFY ("ID_PROYECTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROYECTOS" MODIFY ("NOMBRE_PROYECTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROYECTOS" MODIFY ("FECHA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROYECTOS" MODIFY ("FECHA_FIN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROYECTOS" ADD CONSTRAINT "PROYECTOS_PK" PRIMARY KEY ("ID_PROYECTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RECURSOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RECURSOS" MODIFY ("ID_RECURSO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RECURSOS" MODIFY ("NOMBRE_RECURSO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RECURSOS" MODIFY ("HABILIDADES" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RECURSOS" ADD CONSTRAINT "RECURSOS_PK" PRIMARY KEY ("ID_RECURSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;

--------------------------------------------------------
--  Constraints for Table ASIGNACION_RECURSOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ASIGNACION_RECURSOS" MODIFY ("ID_ASIGNACION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ASIGNACION_RECURSOS" MODIFY ("ID_PROYECTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ASIGNACION_RECURSOS" MODIFY ("ID_RECURSO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ASIGNACION_RECURSOS" ADD CONSTRAINT "ASIGNACION_RECURSOS_PK" PRIMARY KEY ("ID_ASIGNACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;

--------------------------------------------------------
--  Constraints for Table TAREAS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TAREAS" MODIFY ("ID_TAREA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TAREAS" MODIFY ("ID_PROYECTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TAREAS" MODIFY ("NOMBRE_TAREA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TAREAS" MODIFY ("FECHA_VENCIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TAREAS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TAREAS" ADD CONSTRAINT "TAREAS_PK" PRIMARY KEY ("ID_TAREA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;

--------------------------------------------------------
--  Constraints for Table REGISTRO_TIEMPO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REGISTRO_TIEMPO" MODIFY ("ID_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REGISTRO_TIEMPO" MODIFY ("ID_TAREA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REGISTRO_TIEMPO" MODIFY ("ID_RECURSO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REGISTRO_TIEMPO" MODIFY ("TIEMPO_INVERTIDO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REGISTRO_TIEMPO" ADD CONSTRAINT "REGISTRO_TIEMPO_PK" PRIMARY KEY ("ID_REGISTRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAREAS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TAREAS" ADD FOREIGN KEY ("ID_PROYECTO")
	  REFERENCES "SYSTEM"."PROYECTOS" ("ID_PROYECTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASIGNACION_RECURSOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ASIGNACION_RECURSOS" ADD CONSTRAINT "ASIGNACION_PROYECTOS_FK2" FOREIGN KEY ("ID_PROYECTO")
	  REFERENCES "SYSTEM"."PROYECTOS" ("ID_PROYECTO") ENABLE;
  ALTER TABLE "SYSTEM"."ASIGNACION_RECURSOS" ADD CONSTRAINT "ASIGNACION_RECURSOS_FK1" FOREIGN KEY ("ID_RECURSO")
	  REFERENCES "SYSTEM"."RECURSOS" ("ID_RECURSO") ENABLE;


--------------------------------------------------------
--  Ref Constraints for Table REGISTRO_TIEMPO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REGISTRO_TIEMPO" ADD FOREIGN KEY ("ID_TAREA")
	  REFERENCES "SYSTEM"."TAREAS" ("ID_TAREA") ENABLE;
  ALTER TABLE "SYSTEM"."REGISTRO_TIEMPO" ADD FOREIGN KEY ("ID_RECURSO")
	  REFERENCES "SYSTEM"."RECURSOS" ("ID_RECURSO") ENABLE;
